blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/commandlinedev/starterm/issues/new/choose
    about: 'Please post your question on the #starterm discord channel. You may
           also be able to find help at https://users.rust-lang.org/.'
